2-java-script-data-types
js-tasks-ru/js-20230223_masha-verdina pull request #2
Opened 2023-02-28 17:11 UTC by mashaverdina

2023-02-28 17:12 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-03-01 08:59 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  return param === 'asc' ? res : res.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2023-03-01 08:59 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  return param === 'asc' ? res : res.reverse();
что будет если передать `param` отличный от "asc" или "desc"?

2023-03-01 08:59 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  return Object.fromEntries(
good 👍

2023-03-01 08:59 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  return Object.fromEntries(
good 👍

2023-03-01 09:00 UTC, dosandk requested changes
решение sortStrings следует поправить

2023-03-01 09:13 UTC, mashaverdina commented on 02-javascript-data-types/1-sort-strings/index.js
> +  return param === 'asc' ? res : res.reverse();
Будет сортироваться как desc) А что должно быть? Исключение? Тот же массив? Пустой массив? Null? Вроде в тестах и задании по этому поводу ничего не было.

2023-03-01 14:46 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-03-02 12:30 UTC, dosandk approved these changes
👍 good

2023-03-02 12:30 UTC, merged